name: Merge `dev` to `testqa`

on:
  push:
    branches:
      - dev # Trigger the workflow on push to dev

jobs:
  merge-to-testqa:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the full repository history is fetched

      - name: Configure Git
        run: |
          echo "Configuring Git user and email..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          echo "Git configuration complete."

      - name: Ensure `testqa` branch exists
        run: |
          echo "Checking if 'testqa' branch exists..."
          if git fetch origin testqa:testqa; then
            echo "'testqa' branch exists."
          else
            echo "'testqa' branch does not exist. Creating it now..."
            git checkout -b testqa
            git push origin testqa
            echo "'testqa' branch created and pushed."
          fi

      - name: Merge `dev` into `testqa`
        run: |
          echo "Switching to 'testqa' branch..."
          git checkout testqa
          echo "Merging 'dev' into 'testqa'..."
          if git merge origin/dev --no-edit; then
            echo "Merge successful."
          else
            echo "Merge failed due to conflicts or other errors."
            exit 1
          fi

      - name: Push Changes to `testqa`
        run: |
          echo "Pushing changes to 'testqa' branch..."
          if git push origin testqa; then
            echo "Changes successfully pushed to 'testqa' branch."
          else
            echo "Failed to push changes to 'testqa' branch."
            exit 1
          fi

      - name: Merge Status
        run: echo "Merge to 'testqa' completed successfully. Workflow finished."
        if: success()

      - name: Report Failure
        if: failure()
        run: echo "Workflow failed. Please review logs to identify the issue."
