name: Merge `dev` to `testqa`

on:
  push:
    branches:
      - dev # Trigger the workflow on push to dev

jobs:
  merge-to-testqa:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge `dev` into `testqa`
        run: |
          git checkout testqa
          git pull origin testqa
          git merge origin/dev --allow-unrelated-histories --no-edit # Merge dev into testqa
          git push origin testqa  # Push merged changes to testqa

      - name: Push changes to testqa
        run: |
          git push origin testqa  # Ensures that changes are pushed to testqa
