name: Push to testqa

on:
  push:
    branches:
      - dev

jobs:
  push-to-testqa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to testqa branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b testqa || git checkout testqa
          git merge dev
          git push --force origin testqa
